---
functional:
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность авторизоваться
  - Пользователя должен иметь возможность авторизоваться через GitHub
  - Пользователя должен иметь возможность авторизоваться через Discord
  - Пользователь должен иметь возможность менять свой никнейм
  - Пользователь должен иметь возможность создать новую игру с другом или другим пользователем
  - Пользователь должен иметь возможность отправть запрос на игру другу
  - Пользователь должен иметь возможность запустить игру с ботом
  - Пользователь должен иметь возможность выбирать задание для игры
  - Задачи должны быть даны на русском и английском языках
  - Пользователь должен иметь возможность выбирать уровень сложности в игре
  - Пользователь должен иметь возможность выбрать время таймера игры
  - Пользователь должен иметь возможность отправлять сообщения в чате
  - Пользователь должен иметь возможность отправлять личные сообщения другому игроку
  - Пользователь должен иметь возможность видеть код своего соперника в режиме онлайн
  - Во время игры должна быть возможность смены языка программирования на любой из доступных
  - Пользователь должен иметь возможность сдаться и завершить игру
  - Пользователь должен иметь возможность проссматривать баттлы других игроков
  - Пользователь должен иметь возможность просматривать свой рейтинг
  - Пользователь должен иметь возможность проссматривать историю своих игр
  - Пользователь должен иметь возможность просматривать рейтинги других игроков
  - Пользовател должен иметь возможность по доступным тэгам
  - Пользователь должен иметь возможност создать пробную игру без регистрации
  - На странице логина должно быть доступно восстановление пароля
  - Пользователь должен иметь возможность создавать турниры
  - Пользователь должен иметь возможность создавть новые пакеты задач
  - Пользователь должен иметь возможность проссматривать статистику своего профиля
non-functional:
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
implicit:
  - Сайт должен быть доступен на разных языках
  - Пользователь не может редактировать чужой код
